# Generated by Django 5.0.3 on 2024-03-21 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Felhasznalo',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nev', models.CharField(max_length=100)),
                ('szem_ig_szam', models.CharField(max_length=8)),
                ('vez_eng_szam', models.CharField(max_length=9)),
                ('jog_szint_id', models.IntegerField()),
                ('reg_datum', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Foglalas',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('felhasznalo_id', models.IntegerField()),
                ('jarmu_id', models.IntegerField()),
                ('foglalas_kezdete', models.DateTimeField()),
                ('foglalas_vege', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Jarmu',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('rendszam', models.CharField(max_length=7)),
                ('marka', models.CharField(max_length=50)),
                ('tipus', models.CharField(max_length=50)),
                ('szin', models.CharField(max_length=50)),
                ('km_ora_allas', models.IntegerField()),
                ('evjarat', models.DateField()),
                ('muszaki_erv_datum', models.DateField()),
                ('jarmu_kategoria_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='JarmuKategoria',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nev', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='JogosultsagiSzint',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nev', models.CharField(max_length=100)),
            ],
        ),
    ]
