# Generated by Django 5.0.3 on 2024-03-25 19:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jarmu',
            name='kep',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jarmu',
            name='leiras',
            field=models.CharField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
    ]
