# Generated by Django 5.0.3 on 2024-03-25 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_app', '0002_jarmu_kep_jarmu_leiras'),
    ]

    operations = [
        migrations.AlterField(
            model_name='felhasznalo',
            name='jog_szint_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleet_app.jogosultsagiszint'),
        ),
        migrations.AlterField(
            model_name='foglalas',
            name='felhasznalo_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleet_app.felhasznalo'),
        ),
        migrations.AlterField(
            model_name='foglalas',
            name='jarmu_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleet_app.jarmu'),
        ),
        migrations.AlterField(
            model_name='jarmu',
            name='jarmu_kategoria_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleet_app.jarmukategoria'),
        ),
        migrations.AlterField(
            model_name='jarmu',
            name='kep',
            field=models.ImageField(upload_to='static/images/'),
        ),
    ]
