# Generated by Django 5.0.3 on 2024-04-13 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_app', '0003_alter_felhasznalo_jog_szint_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jarmu',
            name='kep',
            field=models.ImageField(upload_to='static/images'),
        ),
    ]
