# Generated by Django 5.0.3 on 2024-04-18 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_app', '0004_alter_jarmu_kep'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marka',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nev', models.CharField(max_length=100)),
            ],
        ),
    ]
