# Generated by Django 5.0.3 on 2024-04-18 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_app', '0005_marka'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jarmu',
            name='marka',
        ),
        migrations.AddField(
            model_name='jarmu',
            name='marka_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='fleet_app.marka'),
            preserve_default=False,
        ),
    ]
